# Generated by Django 4.2 on 2023-04-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
