# Generated by Django 4.2 on 2023-04-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.CharField(default='Default', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='venue',
            field=models.CharField(default='Default', max_length=150),
            preserve_default=False,
        ),
    ]
